### PR TITLE
Move Engine configuration to the app descriptor from the scheme

### PR DESCRIPTION
**Pull request by majecty**
This PR is a part of removing Scheme.

### CODE REVIEW

**Comment by junha1** [comment]
It fails to build

**Comment by majecty** [comment]
@junha1 Sorry, I fixed it.

**Comment by junha1** [comment]
What about this one? https://github.com/majecty/foundry/blob/f/remove-scheme/integration-test/tendermint-solo.json#L6

**Comment by majecty** [comment]
@junha1 Thanks, I removed it.

**Review by junha1 — APPROVED** [review]

**Pull request merged**
