### PR TITLE
Implement IPC for basesandbox

### PR DESCRIPTION
**Pull request by sgkim126**
This PR includes
- 08dcaed34 Assure domain socket's blocking send()
- 08c1c30b6 Refactor common ipc setup
- 081effa42 Allow NotConnected error in socket shutdown
- 815be21c4 Make Executor Send
- 3e54d0f1b Add test for multiplexer
- b44874a0a Implement IPC multiplexer
- 1440f5502 Do not allow duplicated registeration for add_function_pool()
- 64826efd8 Delete explicit socket shutdown
- 13d288875 Make timeouts generous
- 6c151899e Enhance termination protocol of basesandbox execution
- a15abae1a Fix intra to use right terminator
- 4867497e3 Add tests for IPC termination
- 5d75699a2 Add handshake for Intra
- 18152c71e Make executor establish IPC concurrently
- ac5c9c8b2 Add handshake for domain socket constructor
- f93dcdd79 Make domain socket use connect()
- 7a3650943 Change IPC establishment condition
- 6bbac9b85 Move simple.rs from /tests to /tests/simple
- fa38e864e Add a threaded test for Intra
- c0e168b37 Fix the random name generator for IPC
- 120c4ea05 Implement tests for IPC
- a8994ae36 Implement execution of process
- 1df3f4920 Implement intra-process communication that complies IPC interface
- 784b57c18 Implement domain socket
- bc31aa53b Implement abstracted interface of IPC

I reordered and squashed them.

### CODE REVIEW

**Comment by junha1** [comment]
I'm afraid this should belong to https://github.com/CodeChain-io/foundry-sandbox. @dynaxis What do you think?

**Comment by dynaxis** [comment]
@junha1 IPC in our context is closely tied to sandbox mechanisms, so your point seems right here.

**Comment by sgkim126** [comment]
@junha1 Do you mean that foundry-sandbox will implement IPC and the basesandbox in Foundry will use that? If then I'll close this PR.

**Comment by junha1** [comment]
@sgkim126 Yes, and the current implementation in `mold` will be moved there I think.

**Pull request closed without merging**
