### PR TITLE
Implement CreateGeneralMeeting transaction

### PR DESCRIPTION
**Pull request by majecty**

### CODE REVIEW

**Comment by junha1** [comment]
https://discordapp.com/channels/682525519711043609/728140836390305822/742993482267754586

**Comment by majecty** [comment]
@MSNTCS OK, I'll check it.

**Comment by majecty** [comment]
@MSNTCS  This fails clippy error that doesn't related to this PR. I'll add a new PR that pass the clippy check after merging this PR.

**Comment by MSNTCS** [comment]
> @MSNTCS This fails the Clippy tests that aren't related to this PR. I'll add a new PR that passes the Clippy check after merging this PR.

There are some test failures on the coordinator that seems Seulgi is aware of.

**Comment by majecty** [comment]
@MSNTCS Other tests succeed.

**Comment by majecty** [comment]
> There are some test failures on the coordinator that seems Seulgi is aware of.
Then, let's wait for Seulgi. Fix the clippy error later.

**Pull request merged**
