### PR TITLE
Remove needless weight data from Validator

### PR DESCRIPTION
**Pull request by HoOngEe**
In randomized leader election environment, Foundry doesn't need
to manage weight values. Previously, it was utilized to guarantee
stake-proportional leader election but now the property comes from
the nature of the probability model. 
Since this data type change can affect to light client implementation,
I think it's better to be merged earlier.

### CODE REVIEW

**Comment by sgkim126** [comment]
Does the RLE treat all validators have the same vote?
What does happen if the major number of validators agreed, but the major amount of stakes does not?

**Comment by HoOngEe** [comment]
`Validator` struct has both `weight` and `delegation` fields. When the struct is initialized, both are set to one equal value. `weight` value decreases as rounds proceed and `Validators` were re-sorted by `weight` values. It wasn't used to measure voting power but just helped leader elections in weighted round-robin fashion. Still voting power can be measured using the `delegation` field.

**Comment by sgkim126** [comment]
@HoOngEe Would you check e2e tests?

**Comment by HoOngEe** [comment]
I'm sorry, I was day off yesterday. I'll check it.

**Comment by HoOngEe** [comment]
I'm sorry, this commit can not be solely applied to the master. If the weight data is removed, the round-robin fashioned election will not work so that almost all the tests related to dynamic validator will fail because there is only one fixed validator.

**Comment by HoOngEe** [comment]
I think this issue can only be merged into master when Tenderand becomes the main consensus of Foundry unavoidably.

**Pull request closed without merging**
