### PR TITLE
Implement coordinator contexts for the client

### PR DESCRIPTION
**Pull request by sgkim126**
~It depends on https://github.com/CodeChain-io/foundry/pull/405~

### CODE REVIEW

**Comment by majecty** [comment]
I'll review this PR after 405 is merged.

**Comment by majecty** [comment]
@sgkim126 Could you rebase on the master?

**Comment by sgkim126** [comment]
@majecty @somniumism I rebased it.

**Comment by somniumism** [comment]
It's not a problem right now, but the Distribution module also needs `.seal()`. Let's add it later when we need it. Everything else looks good to me.

**Pull request merged**
