### PR TITLE
Remove Store/Remove transactions

### PR DESCRIPTION
**Pull request by dynaxis**
Resolves most of #17 except for removal of cost settings for those transactions.

### CODE REVIEW

**Comment by majecty** [comment]
Looks good to me. It was easy to review this PR since you separated all commits very well. What do you think about squashing all this commits after Seulgi reviews this PR?

**Comment by sgkim126** [comment]
LGTM too and I agree on @majecty's idea squashing all commits.

**Comment by dynaxis** [comment]
It's ok to squash all the commits into one. Since there have been a few commits pushed to the master in the mean time, I'll rebase, squash all the commits together, and force push the change. Then please merge it.

**Comment by dynaxis** [comment]
Done. Please merge it. Thanks for the reviews.

**Comment by sgkim126** [comment]
I checked that there are no changes except merging the commits. I'll merge it.

**Pull request merged**
