### PR TITLE
Add simple description of how to use GraphQL

### PR DESCRIPTION
**Pull request by majecty**

### CODE REVIEW

**Comment by junha1** [comment]
`/_graph_graphql` is for Graph***i***QL web page. Service programs will usually access to `/graphql` directly.
Would you clarify this?

**Comment by majecty** [comment]
@junha1 OK, I'll update it.

**Comment by majecty** [comment]
@junha1 I've updated it.

**Review by junha1 — APPROVED** [review]

**Comment by majecty** [comment]
This PR is not related to unit tests. I'll merge it.

**Pull request merged**
