### PR TITLE
Implement MemPoolAccess as a part of the context

### PR DESCRIPTION
**Pull request by HoOngEe**
~~It can only be merged after @Byeongjee 's branch `byeongjee/implement.validator.interface.call` is landed.
This pr includes only one commit `80bdd5`~~

### CODE REVIEW

**Comment by HoOngEe** [comment]
This work requires the type change of the argument `transaction` in the method `Client::queue_own_transaction`

**Comment by HoOngEe** [comment]
I think that's because I had worked on the old branch, I'll update the pr.

**Comment by HoOngEe** [comment]
@Byeongjee Ok, we firstly have to list up the errors that can be handled by modules. I think it's better to make a crate for such shared types.

**Comment by Byeongjee** [comment]
> @Byeongjee Ok, we firstly have to list up the errors that can be handled by modules. I think it's better to make a crate for such shared types.

Maybe we can reuse `codechain-types` crate.

**Comment by Byeongjee** [comment]
@HoOngEe Currently, the only error types currently available are
1.  `HistoryError::TransactionAlreadyImported`
2. `HistoryError::LimitReached`
3. `AppError(err_code)` (where `err_code` is a typical integer)

Note that `TransactionAlreadyImported` can be emitted in two cases
1. The transaction is already imported in the chain
2. The transaction is already imported in the mempool, but not included in a block yet.

`AppError` will be responsible for handling all other kinds of errors, including `HistoryError::Old` and `HistoryError::TooCheapToReplace`, etc.

Note that the error code of `AppError` is defined by modules, so the modules should know about the meaning of each error code, and are responsible for handling them.

If you think it's better to merge the error types into one, please let me know.

**Comment by Byeongjee** [comment]
@HoOngEe How do you think about closing this PR now, and implement new error types, when we are actually implementing the error handling logic?

**Pull request merged**
